version: '3'
services:
  api:
    image: cybercyclonic/notes-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}

    links:
      - mongodb

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

    volumes:
      - db:/data/db





volumes:
  db:

