version: '3'
services:
  api:
    image: cybercyclonic/notes-app-api:dev
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}

    volumes:
      - server:/usr/src/app

    links:
      - mongodb

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

    volumes:
      - db:/data/db





volumes:
  db:
  server:
